# GoReleaser configuration for Agent Deck
# Run: goreleaser release --clean
# Test: goreleaser release --snapshot --clean

version: 2

project_name: agent-deck

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: agent-deck
    main: ./cmd/agent-deck
    binary: agent-deck
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
    # Skip Windows - tmux not available
    ignore:
      - goos: windows

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: asheshgoplani
    name: agent-deck
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## Agent Deck v{{.Version}}

    Terminal session manager for AI coding agents.

    ### Installation

    **Quick Install (recommended):**
    ```bash
    curl -fsSL https://raw.githubusercontent.com/asheshgoplani/agent-deck/main/install.sh | bash
    ```

    **Go Install:**
    ```bash
    go install github.com/asheshgoplani/agent-deck/cmd/agent-deck@v{{.Version}}
    ```

    **From Source:**
    ```bash
    git clone https://github.com/asheshgoplani/agent-deck.git
    cd agent-deck && make install
    ```
